In [1]:
# imports
import numpy as np

In [2]:
# task_1
a = np.array([1, 1, 2, 1, 2, 3, 3, 3, 4, 4, 4, 4])
print(a)

values, counts = np.unique(a, return_counts=True)
dict_count = dict(zip(values, counts))

print(np.array(sorted(a, key=lambda x: dict_count[x])))

[1 1 2 1 2 3 3 3 4 4 4 4]
[2 2 1 1 1 3 3 3 4 4 4 4]


In [3]:
# task_2
h, w = map(int, input().split())
img = np.random.randint(0, 256, (h, w, 3), dtype=np.uint8)

print(len(np.unique(img.reshape(-1, 3), axis=0)))


59886


In [4]:
# task_3
def moving_average(a, n=3):
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n

print(np.arange(20))
print(moving_average(np.arange(20), n=4))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1.5  2.5  3.5  4.5  5.5  6.5  7.5  8.5  9.5 10.5 11.5 12.5 13.5 14.5
 15.5 16.5 17.5]


In [ ]:
# task_4
n = int(input())
a = np.random.randint(1, 1000, size=(n, 3))

mask = (
    (a[:, 0] < a[:, 1] + a[:, 2]) &
    (a[:, 1] < a[:, 0] + a[:, 2]) &
    (a[:, 2] < a[:, 0] + a[:, 1])
)

triangles = a[mask]

print(a)
print("----------")
print(triangles)


ValueError: invalid literal for int() with base 10: ''

In [6]:
# task_5
k = np.array([
    [3, 4, 2],
    [5, 2, 3],
    [4, 3, 2]
], dtype=float)

z = np.array([17, 23, 19], dtype=float)

np.dot(np.linalg.inv(k), z)

array([3., 1., 2.])

In [7]:
# task_6
A = np.matrix("1 0 1; 0 1 0; 1 0 1")

U, S, Vh = np.linalg.svd(A)
print(f'{U}\n{S}\n{Vh}')

[[-0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [-0.70710678  0.          0.70710678]]
[2. 1. 0.]
[[-0.70710678  0.         -0.70710678]
 [ 0.          1.          0.        ]
 [ 0.70710678  0.         -0.70710678]]
